apiVersion: apps/v1
kind: Deployment
metadata:
  name: ticketing-ticket-depl
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ticket
  template:
    metadata:
      labels:
        app: ticket
    spec:
      containers:
        - name: ticket
          image: hridooy/ticketing_ticket
          env:
            - name: TICKETING_TICKET_JWT_KEY
              valueFrom:
                secretKeyRef:
                  name: ticketing
                  key: JWT_KEY
            - name: TICKETING_TICKET_DB_HOST
              value: auth-mongo-srv
            - name: TICKETING_NATS_CLUSTER_ID
              value: 'ticketing'
            - name: TICKETING_TICKET_NATS_CLIENT_ID
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: TICKETING_NATS_URL
              value: 'http://nats-srv:4222' 
          resources:
            limits:
              memory: "512Mi"
              cpu: "512m"
---
apiVersion: v1
kind: Service
metadata:
  name: ticketing-ticket-srv
spec:
  selector:
    app: ticket
  ports:
    - port: 3000
      targetPort: 3000
      name: ticket
      protocol: TCP
